<?php
    $PROGRAM_START = "PROGRAM_START";
    $PROGRAM_END = "PROGRAM_END";
    $STUDY_CENTER_START = "STUDY_CENTER_START";
    $STUDY_CENTER_END = "STUDY_CENTER_END";
    $EMPLOYEE_CODE_START = "EMPLOYEE_CODE_START";
    $EMPLOYEE_CODE_END = "EMPLOYEE_CODE_END";
    $CONVERSATION_DETAILS_START = "CONVERSATION_DETAILS_START";
    $CONVERSATION_DETAILS_END = "CONVERSATION_DETAILS_END";
    $EMAIL_TEMPLATE_START = "EMAIL_TEMPLATE_START";
    $EMAIL_TEMPLATE_END = "EMAIL_TEMPLATE_END";
    $NOTIFICATION_DATA_START = "NOTIFICATION_DATA_START";
    $NOTIFICATION_DATA_END = "NOTIFICATION_DATA_END";
    $COOKIE_TIME = time() + (150);
    $DEMILINATOR = "|";

?>